[versions]
kotlin = "2.3.10"
ktor = "3.4.0"
exposed = "1.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.31" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-javaTime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version = "2.4.240" }
hikari = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
