name: Benchmarks (Base Branch)

on:
  push:
    branches:
      - main

permissions:
  checks: write

jobs:
  benchmark_base_branch:
    name: Bencher (Base Branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
      - name: Run benchmarks
        id: run
        run: |
          ./gradlew benchmark
          echo "result_file=$(find . -type f -name 'jvm.json')" >> $GITHUB_OUTPUT
      - uses: bencherdev/bencher@main
      - name: Track benchmark result with Bencher
        run: |
          bencher run \
          --project d1158d5b-df59-4769-9ff0-8b2fd3d648b0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure throughput \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-lower-boundary 0.99 \
          --threshold-upper-boundary _ \
          --thresholds-reset \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter java_jmh --file ${{ steps.run.outputs.result_file }}
